import type { NextConfig } from "next";
import createNextIntlPlugin from "next-intl/plugin";

const withNextIntl = createNextIntlPlugin("./src/lib/i18n/request.ts");

const nextConfig: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  typedRoutes: true,
  /** `public/favicon.ico` is generated by `pnpm run build:icons` from `brand/bytloop-mark.svg`. */
  // Next.js 16 uses Turbopack by default; next-intl's plugin only sets
  // `experimental.turbo.resolveAlias`, which is not applied — alias must
  // exist on `turbopack` or `next-intl/config` resolves to a stub and throws.
  turbopack: {
    resolveAlias: {
      "next-intl/config": "./src/lib/i18n/request.ts",
    },
  },
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "Permissions-Policy", value: "geolocation=(), microphone=(), camera=()" },
          { key: "Cross-Origin-Opener-Policy", value: "same-origin" },
          { key: "Cross-Origin-Resource-Policy", value: "same-site" },
        ],
      },
    ];
  },
  // Backend URL for server-side fetches (RSC → FastAPI).
  env: {
    NEXT_PUBLIC_API_BASE_URL:
      process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000",
  },
};

export default withNextIntl(nextConfig);
